name: /home/path_sam3/conda_envs/path_sam3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - debugpy=1.8.16=py312h8285ef7_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=hecca717_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgomp=15.2.0=he0feb66_17
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.0=hd590300_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h8a09558_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py312h4c3975b_1
  - pthread-stubs=0.3=1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python_abi=3.12=3_cp312
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=heff268d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py312h66e93f0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.4.0
      - annotated-doc==0.0.4
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - certifi==2026.1.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - decord==0.6.0
      - einops==0.8.2
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - ftfy==6.1.1
      - fvcore==0.1.5.post20221221
      - grpcio==1.78.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - hydra-core==1.3.2
      - idna==3.11
      - iopath==0.1.10
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.3
      - markdown==3.10.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.13.0.92
      - pandas==3.0.1
      - pillow==12.0.0
      - portalocker==3.2.0
      - protobuf==6.33.5
      - pyarrow==23.0.0
      - pycocotools==2.0.11
      - pyparsing==3.3.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - rich==14.3.2
      - safetensors==0.7.0
      - sam3==0.1.0
      - scipy==1.17.1
      - shellingham==1.5.4
      - socksio==1.0.0
      - submitit==1.5.4
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - timm==1.0.24
      - torch==2.7.0+cu126
      - torchaudio==2.7.0+cu126
      - torchmetrics==1.8.2
      - torchvision==0.22.0+cu126
      - tqdm==4.67.3
      - triton==3.3.0
      - typer==0.24.0
      - typer-slim==0.24.0
      - werkzeug==3.1.6
      - yacs==0.1.8
prefix: /home/path_sam3/conda_envs/path_sam3
